apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongo-config
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            exec:
              command: ["sh", "-c", "mongo --eval \"db.adminCommand('ping')\""]
            initialDelaySeconds: 10
            periodSeconds: 5
