apiVersion: v1
kind: ConfigMap
metadata:
  name: app-preparation-config
data:
  # FIX o ClusterIP do BD não deveria ser hardcoded
  DATABASE_URL: mongodb://fast-food:strongpassword@mongo-service:27017/fast-food-preparation
