apiVersion: v1
kind: Service
metadata:
  name: app-preparation-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
